baseURL: https://blog.st2projects.com
languageCode: en-us
title: Blog | ST2 Projects
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
publishdir: public

minify:
  disableXML: true

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Archive
      url: archives
      weight: 2
    - name: Categories
      url: categories/
      weight: 3
    - name: Tags
      url: tags/
      weight: 4
    - name: Search
      url: search/
      weight: 5

params:
  description: "Stuff"
  author:
  keywords: [ Blog, Programming, Hugo ]
  env: production

  defaultTheme: auto
  images:
    - post-cover.png
  homeInfoParams:
    Title: Hi there 👋
    Content: >
      - This is a dumping ground of thoughts, ideas and other things
      
      - <br>
      
      - This is not a blog, or a wiki... I don't know what it is... but it is a thing
      
      - _Ceci n’est pas une pipe_

  socialIcons:
    - name: github
      url: https://github.com/neo1908
    - name: gitlab
      url: https://gitlab.com/Kathyikka

  outputs:
    home:
      - HTML
      - RSS
      - JSON
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]

  showShareButtons: true
  showReadingTime: true
  showToc: true
  showBreadCrumbs: true
  comments: false

  editPost:
    URL: "https://gitlab.com/Kathyikka/pages/blob/main/content"
    Text: "Suggest Edits"
    appendFilePath: true # to append file path to Edit link

  showPostNavLinks: true
  showCodeCopyButtons: true

  assets:
    disableHLJS: true

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    lineNos: false
    style: monokai
  goldmark:
    renderer:
      hardWraps: True
